add_executable(test_typing test_typing.cpp)
target_link_libraries(test_typing PRIVATE openkey_core)
target_include_directories(test_typing PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
add_test(NAME typing COMMAND test_typing)

find_package(PkgConfig REQUIRED)
pkg_check_modules(TEST_XKBCOMMON REQUIRED IMPORTED_TARGET xkbcommon)
add_executable(test_driver test_driver.cpp)
target_link_libraries(test_driver PRIVATE openkey_driver PkgConfig::TEST_XKBCOMMON)
add_test(NAME driver COMMAND test_driver)
